### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by harshraj22** [jaideeppyne/leetcode-problem-solving#10]
https://github.com/jaideeppyne/leetcode-problem-solving/blob/692fedbf2621bc841d90d2d00a16c2b26f1adfea/MayChallenge/cpp/Remove%20K%20Digits#L33

This answer gives Segmentation Fault on testcase:
```
"1432219"
3
```

**Comment by jaideeppyne** [comment]
Fixed. You can continue now.
